[Interface]
PrivateKey = eAfVTVjWaQOzkK6ISb0Aoo6bDwhjIy1eLyrOafbZK0Q=
Address = 10.0.0.101/24

[Peer]
PublicKey = dnAM66dzn9wM+NLg5Rnb3mRX808nWBTEPaaTdncYHk0=
AllowedIPs = 10.0.0.0/24
Endpoint = 172.27.227.112:51820
PersistentKeepalive = 25
